---
- name: Setup the Networking namespace
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 00-namespace.yml}

- name: Add metallb helm repo
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Deploy metallb chart
  community.kubernetes.helm:
    name: metallb
    chart_ref: bitnami/metallb
    chart_version: 2.3.5
    values: "{{ lookup('template', 'metallb/01-chart-values.yml') | from_yaml }}"
    release_namespace: networking
    update_repo_cache: true
    wait: true
