---
- name: Setup the Networking namespace
  k8s:
    definition: "{{ lookup('template', '00-namespace.yml') | from_yaml }}"
    state: present
    wait: true

# ------------------------------------------------------------------------------

- name: Add metallb helm repo
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
    state: present

- name: Deploy metallb chart
  community.kubernetes.helm:
    name: metallb
    chart_ref: bitnami/metallb
    chart_version: 2.3.5
    values: "{{ lookup('template', 'metallb/01-chart-values.yml') | from_yaml }}"
    release_namespace: networking
    update_repo_cache: true
    wait: true

# ------------------------------------------------------------------------------

- name: Setup Unbound
  k8s:
    definition: "{{ lookup('template', item) | from_yaml }}"
    state: present
    wait: true
  loop:
  - unbound/01-configmap.yml
  - unbound/02-service-tcp.yml
  - unbound/03-service-udp.yml
  - unbound/04-deployment.yml

# ------------------------------------------------------------------------------
- name: Create temporary file
  ansible.builtin.tempfile:
    state: file
    prefix: traefik
  register: basicAuthFile

- name: Add a user to a password file suitable for use by libpam-pwdfile
  community.general.htpasswd:
    path: '{{ basicAuthFile.path }}'
    name: '{{ traefik_admin_user }}'
    password: '{{ traefik_admin_password }}'
    crypt_scheme: md5_crypt

- name: Start Traefik setup
  k8s:
    definition: "{{ lookup('template', item) | from_yaml }}"
    state: present
    wait: true
  loop:
  - traefik/01-secret-cloudflare.yml
  - traefik/02-configmap.yml

- name: Add Traefik helm repo
  community.kubernetes.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: Deploy Traefik chart on 9.13.0 with values loaded from template
  community.kubernetes.helm:
    name: traefik
    chart_ref: traefik/traefik
    chart_version: 9.13.0
    values: "{{ lookup('template', 'traefik/03-chart-values.j2') | from_yaml }}"
    release_namespace: networking
    update_repo_cache: true
    wait: true

- name: Finish Traefik setup
  vars:
    basicAuthPasswords: "{{ lookup('file', basicAuthFile.path) | b64encode }}"
  k8s:
    definition: "{{ lookup('template', item) | from_yaml }}"
    state: present
    wait: true
  loop:
  - traefik/04-secret-dashboard.yml
  - traefik/05-middleware.yml
  - traefik/06-ingress.yml

# ------------------------------------------------------------------------------

- name: Add pihole helm repo
  community.kubernetes.helm_repository:
    name: pihole
    repo_url: https://mojo2600.github.io/pihole-kubernetes

- name: Deploy pihole chart
  community.kubernetes.helm:
    name: pihole
    chart_ref: pihole/pihole
    chart_version: 1.8.29
    values: "{{ lookup('template', 'pihole/01-chart-values.yml') | from_yaml }}"
    release_namespace: networking
    update_repo_cache: true
    wait: true

- name: Finish pihole setup
  k8s:
    definition: "{{ lookup('template', item) | from_yaml }}"
    state: present
    wait: true
  loop:
  - pihole/02-middleware.yml
  - pihole/03-ingress.yml
