---
- name: Remove metallb release
  community.kubernetes.helm:
    name: metallb
    purge: true
    release_namespace: networking
    state: absent
    wait: true

- name: Delete the Networking namespace
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: absent
    wait: true
  with_items:
  - {type: template, path: 00-namespace.yml}
