---
- name: Setup the DNS namespace
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 00-namespace.yml}
