---
- name: Setup InfluxDB
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 01-secret.yml}
  - {type: template, path: 02-pvc.yml}
  - {type: template, path: 03-service.yml}
  - {type: template, path: 04-deployment.yml}
