---
- name: Start InfluxDB setup
  k8s:
    definition: '{{ lookup( item.type, item.path, split_lines=False ) | from_yaml_all | list }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 00-secret.yml}

- name: Add Influx Data helm repo
  community.kubernetes.helm_repository:
    name: influxdata
    repo_url: https://helm.influxdata.com/

- name: Deploy InfluxDB chart
  community.kubernetes.helm:
    name: influxdb
    chart_ref: influxdata/influxdb
    chart_version: 4.9.14
    values: "{{ lookup('template', '00-chart-values.yml') | from_yaml }}"
    release_namespace: monitoring
    update_repo_cache: true
    create_namespace: true
    wait: true
    wait_timeout: 500s

- name: Finish InfluxDB setup
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 01-middleware.yml}
  - {type: template, path: 02-ingress.yml}

- name: Pause play until the InfluxDB URL is reachable from this host
  uri:
    url: https://monitoring.{{ domain_name }}/db/health
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: 720  # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5  # Every 5 seconds
