---
- name: Start InfluxDB setup
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 00-secret.yml}

- name: Add Influx Data helm repo
  community.kubernetes.helm_repository:
    name: influxdata
    repo_url: https://helm.influxdata.com/

- name: Deploy InfluxDB chart
  community.kubernetes.helm:
    name: influxdb
    chart_ref: influxdata/influxdb
    chart_version: 4.9.14
    values: "{{ lookup('template', '01-chart-values.yml') | from_yaml }}"
    release_namespace: monitoring
    update_repo_cache: true
    create_namespace: true
    wait: true
    wait_timeout: 500s

- name: Finish InfluxDB setup
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 02-middleware.yml}
  - {type: template, path: 03-ingress.yml}

- name: Pause play until the InfluxDB URL is reachable from this host
  uri:
    url: https://monitoring.{{ domain_name }}/db/health
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: 720  # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5  # Every 5 seconds

- name: Setup InfluxDB databases
  community.general.influxdb_database:
    hostname: monitoring.{{ domain_name }}
    path: /db
    port: 443
    ssl: true
    validate_certs: false
    username: '{{ influxdb_username }}'
    password: '{{ influxdb_password }}'
    database_name: '{{ item }}'
  with_items:
  - '{{ telegraf_cluster_db }}'

- name: Create InfluxDB users for writing data
  community.general.influxdb_user:
    user_name: '{{ item.user }}'
    user_password: '{{ item.pass }}'
    login_username: '{{ influxdb_username }}'
    login_password: '{{ influxdb_password }}'
    hostname: monitoring.{{ domain_name }}
    path: /db
    port: 443
    ssl: true
    validate_certs: false
    grants:
    - database: '{{ item.database }}'
      privilege: '{{ item.privilege }}'
  with_items:
  # yamllint disable-line rule:line-length
  - {user: '{{ telegraf_cluster_db_user }}', pass: '{{ telegraf_cluster_db_pass }}', privilege: WRITE, database: '{{ telegraf_cluster_db }}'}

- name: Create InfluxDB user for grafana with read privilege
  community.general.influxdb_user:
    user_name: '{{ grafana_db_user }}'
    user_password: '{{ grafana_db_pass }}'
    login_username: '{{ influxdb_username }}'
    login_password: '{{ influxdb_password }}'
    hostname: monitoring.{{ domain_name }}
    path: /db
    port: 443
    ssl: true
    validate_certs: false
    grants:
    - database: '{{ telegraf_cluster_db }}'
      privilege: READ
