---
- name: Setup Metal LB
  vars:
    metallb_secret: '{{ lookup("password", "/dev/null length=128") | b64encode }}'
  k8s:
    definition: '{{ lookup(item.type, item.path, split_lines=False) | from_yaml_all | list  }}'
    state: present
    wait: true
  with_items:
  # yamllint disable-line rule:line-length
  - {type: url, path: 'https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/namespace.yaml'}
  - {type: template, path: 01-secret.yml}
  - {type: template, path: 02-configmap.yml}
  - {type: url, path: 'https://raw.githubusercontent.com/google/metallb/{{ metallb_version }}/manifests/metallb.yaml'}
