---
adminPassword: '{{ pihole_web_password }}'
DNS1: '{{ unbound_addr }}'
DNS2: 127.0.0.1
extraEnvVars:
  TZ: '{{ timezone }}'
serviceDns:
  loadBalancerIP: '{{ pihole_addr }}'
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
