---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound-svc
  name: svc-dns-unbound-tcp
  namespace: dns-system
spec:
  loadBalancerIP: '{{ unbound_addr }}'
  ports:
  - port: 53
    targetPort: 5053
    protocol: TCP
    name: dns-tcp
  selector:
    app: unbound
  type: LoadBalancer
