---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound-svc
  name: unbound-dns-udp
  namespace: dns-system
spec:
  loadBalancerIP: '{{ unbound_addr }}'
  ports:
  - port: 53
    targetPort: 5053
    protocol: UDP
    name: dns-udp
  selector:
    app: unbound
  type: LoadBalancer
