---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
