---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
spec:
  loadBalancerIP: '{{ influxdb_addr }}'
  ports:
  - name: ingest-tcp
    port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: influxdb
  type: LoadBalancer
