---
- name: Remove Metal LB
  k8s:
    definition: '{{ lookup(item.type, item.path, split_lines=False) | from_yaml_all | list  }}'
    state: absent
    wait: true
  with_items:
  - {type: url, path: 'https://raw.githubusercontent.com/google/metallb/{{ metallb_version }}/manifests/metallb.yaml'}
  # yamllint disable-line rule:line-length
  - {type: url, path: 'https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/namespace.yaml'}
