---
nfs:
  server: '{{ nfs_server_addr }}'
  path: '{{ nfs_server_path }}'
image:
  repository: coppertopgeoff/nfs-subdir-external-provisioner
  tag: arm-linux-canary
storageClass:
  pathPattern: ${.PVC.namespace}/${.PVC.name}
  archiveOnDelete: false
  reclaimPolicy: Retain
