---
# ansible
ansible_user: user

# k3s
k3s_version: v1.19.4+k3s1
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: --disable=servicelb,traefik --flannel-backend=host-gw
extra_agent_args: ''

# Metal LB
metallb_version: v0.9.5
metallb_start_addr: 192.168.1.70
metallb_end_addr: 192.168.1.99

# Unbound
unbound_addr: 192.168.1.70
unbound_version: 1.13.1

# Traefik
domain_name: example.com
traefik_addr: 192.168.1.72

# Helm
helm_url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

# ACME
acme_prod_url: https://acme-v02.api.letsencrypt.org/directory
acme_staging_url: https://acme-staging-v02.api.letsencrypt.org/directory
acme_dns_delay: 120
acme_dns_provider: cloudflare
acme_dns_resolver: 1.1.1.1
acme_email: example@example.com
acme_issuer: staging

# Cloudfare
cloudflare_api_email: example@example.com
cloudflare_api_key: 66c7bbbb8888a99aaa9b8c7d6b90e1375b92c
