---
# ansible
ansible_user: user

# k3s
k3s_version: v1.19.4+k3s1
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: --disable=servicelb,traefik --flannel-backend=host-gw
extra_agent_args: ''

# Metal LB
metallb_version: v0.9.5
metallb_start_addr: 192.168.1.70
metallb_end_addr: 192.168.1.99

# Unbound
unbound_addr: 192.168.1.70
unbound_version: 1.13.1

# Traefik
domain_name: example.com
traefik_addr: 192.168.1.72

# Helm
helm_url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
