---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: networking
type: Opaque
stringData:
  CF_API_EMAIL: '{{ cloudflare_api_email }}'
  CF_API_KEY: '{{ cloudflare_api_key }}'
