---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: networking
type: Opaque
stringData:
  email: '{{ cloudflare_api_email }}'
  apiKey: '{{ cloudflare_api_key }}'
