---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: networking
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`traefik.{{ domain_name }}`)
    kind: Rule
    middlewares:
    - name: traefik-dashboard-basicauth
      namespace: networking
    services:
    - name: api@internal
      kind: TraefikService
