---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-sensor-bridge
  namespace: apps
  labels:
    app: weather-sensor-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-sensor-bridge
  template:
    metadata:
      labels:
        app: weather-sensor-bridge
    spec:
      containers:
      - name: weather-sensor-bridge
        image: ghcr.io/geoff-coppertop/weather-sensor-bridge:0.0.6
        imagePullPolicy: Always
        resources:
          requests:
            smarter-devices/bus_usb_001_004: 1
          limits:
            smarter-devices/bus_usb_001_004: 1
        env:
        - name: DEBUG
          value: warn
        - name: SERVER_URL
          value: mqtt://mqtt.data.svc:1883
        - name: KA_TIME
          value: '10'
        - name: CRD_TIME
          value: '100'
