---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wunderground-uploader
  namespace: apps
  labels:
    app: wunderground-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wunderground-uploader
  template:
    metadata:
      labels:
        app: wunderground-uploader
    spec:
      containers:
      - name: wunderground-uploader
        image: ghcr.io/geoff-coppertop/wunderground-uploader:0.0.2
        imagePullPolicy: Always
        env:
        - name: DEBUG
          value: debug
        - name: SERVER_URL
          value: mqtt://mqtt.data.svc:1883
        - name: KA_TIME
          value: '10'
        - name: CRD_TIME
          value: '100'
        - name: TOPIC
          value: sensor/rtl_433/SwitchDoc_Labs_FT020T_AIO/0_000000
        - name: STATION_ID
          value: ICOCHR19
        - name: STATION_KEY
          value: QTonFEwY
