---
- name: Fetch the kube config from the master node
  fetch:
    src: ~{{ ansible_user }}/.kube/config
    dest: ~/.kube/config
    flat: true
  delegate_to: "{{ groups['master'][0] }}"

- name: Lockdown kube config to the current user
  ansible.builtin.file:
    path: ~/.kube/config
    mode: '0600'

- name: Install dependent packages for cluster setup and control
  community.general.homebrew:
    name: '{{ item }}'
    state: present
  with_items:
  - helm
  - kubectl
