---
apiVersion: v1
kind: Secret
metadata:
  name: influx-admin
  namespace: monitoring
type: Opaque
stringData:
  influxdb-user: '{{ influxdb_username }}'
  influxdb-password: '{{ influxdb_password }}'
