---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb
  namespace: monitoring
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`monitoring.{{ domain_name }}`) && PathPrefix(`/db`)
    kind: Rule
    middlewares:
    - name: influxdb-strip
      namespace: monitoring
    services:
    - name: influxdb
      port: 8086
