---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-admin
  namespace: monitoring
data:
  admin-user: '{{ grafana_admin_user | b64encode }}'
  admin-password: '{{ grafana_admin_password | b64encode }}'
