---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homer
  namespace: apps
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`{{ domain_name }}`)
    kind: Rule
    services:
    - name: homer
      port: 80
