---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: apps
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
      - name: homer
        image: b4bz/homer:21.03.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /www/assets
          name: homer-assets
      volumes:
      - name: homer-assets
        configMap:
          name: homer
