---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kanboard
  namespace: apps
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`kanboard.{{ domain_name }}`)
    kind: Rule
    services:
    - name: kanboard
      port: 80
