---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kanboard
  namespace: apps
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
