---
apiVersion: v1
kind: Secret
metadata:
  name: kanboard
  namespace: apps
type: Opaque
stringData:
  DATABASE_URL: postgres://{{ kanboard_db_user }}:{{ kanboard_db_pass }}@postgresql.data.svc/{{ kanboard_db_name }}
