---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
  namespace: apps
  labels:
    app: kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      labels:
        app: kanboard
    spec:
      containers:
      - name: kanboard
        image: kanboard/kanboard:v1.2.20
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: kanboard
        volumeMounts:
        - mountPath: /var/www/app/data
          name: kanboard-app-data
        - mountPath: /var/www/app/plugins
          name: kanboard-app-plugins

      # These containers are run during pod initialization
      initContainers:
      - name: git-cloner-nebula
        image: alpine/git:v2.30.2
        imagePullPolicy: IfNotPresent
        args:
        - clone
        - --depth
        - '1'
        - --branch
        - 1.3.6
        - --
        - https://github.com/kenlog/Nebula.git
        - /data/Nebula
        volumeMounts:
        - mountPath: /data
          name: kanboard-app-plugins

      - name: git-cloner-customizer
        image: alpine/git:v2.30.2
        imagePullPolicy: IfNotPresent
        args:
        - clone
        - --depth
        - '1'
        - --branch
        - 1.13.7
        - --
        - https://github.com/creecros/Customizer.git
        - /data/Customizer
        volumeMounts:
        - mountPath: /data
          name: kanboard-app-plugins

      volumes:
      - name: kanboard-app-data
        persistentVolumeClaim:
          claimName: kanboard
      - name: kanboard-app-plugins
        emptyDir: {}
