---
- name: Grafana pre-setup tasks
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 00-secret.yml}

- name: Add grafana helm repo
  community.kubernetes.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Deploy grafana chart
  community.kubernetes.helm:
    name: grafana
    chart_ref: grafana/grafana
    chart_version: 6.4.6
    values: "{{ lookup('template', '01-chart-values.yml') | from_yaml }}"
    release_namespace: monitoring
    update_repo_cache: true
    create_namespace: true
    wait: true
