---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: apps
  labels:
    app: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
      - name: wikijs
        image: requarks/wiki:2.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql.data.svc
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: '{{ wikijs_db_user }}'
        - name: DB_NAME
          value: '{{ wikijs_db_name }}'
        envFrom:
        - secretRef:
            name: wikijs
