---
- name: Setup the apps namespace
  k8s:
    definition: "{{ lookup( 'template', '00-namespace.yml' ) | from_yaml }}"
    state: present
    wait: true

# ------------------------------------------------------------------------------

- name: Setup DB for kanboard
  community.postgresql.postgresql_db:
    name: '{{ kanboard_db_name }}'
    state: present
    maintenance_db: postgres
    login_host: '{{ postgresql_addr }}'
    login_user: postgres
    login_password: '{{ postgresql_admin_pass }}'

- name: Setup user for kanboard
  community.postgresql.postgresql_user:
    db: '{{ kanboard_db_name }}'
    priv: ALL
    name: '{{ kanboard_db_user }}'
    password: '{{ kanboard_db_pass }}'
    state: present
    login_host: '{{ postgresql_addr }}'
    login_user: postgres
    login_password: '{{ postgresql_admin_pass }}'

- name: Setup kanboard
  k8s:
    definition: "{{ lookup( 'template', item ) | from_yaml }}"
    state: present
    wait: true
  loop:
  - kanboard/00-service.yml
  - kanboard/01-ingress.yml
  - kanboard/02-pvc.yml
  - kanboard/03-secret.yml
  - kanboard/04-deployment.yml

# ------------------------------------------------------------------------------

- name: Setup DB for wiki-js
  community.postgresql.postgresql_db:
    name: '{{ wikijs_db_name }}'
    state: present
    maintenance_db: postgres
    login_host: '{{ postgresql_addr }}'
    login_user: postgres
    login_password: '{{ postgresql_admin_pass }}'

- name: Setup user for wiki-js
  community.postgresql.postgresql_user:
    db: '{{ wikijs_db_name }}'
    priv: ALL
    name: '{{ wikijs_db_user }}'
    password: '{{ wikijs_db_pass }}'
    state: present
    login_host: '{{ postgresql_addr }}'
    login_user: postgres
    login_password: '{{ postgresql_admin_pass }}'

- name: Setup wiki-js
  k8s:
    definition: "{{ lookup( 'template', item ) | from_yaml }}"
    state: present
    wait: true
  loop:
  - wiki-js/00-service.yml
  - wiki-js/01-ingress.yml
  - wiki-js/02-secret.yml
  - wiki-js/03-deployment.yml

# ------------------------------------------------------------------------------

- name: Setup homer
  k8s:
    definition: "{{ lookup( 'template', item ) | from_yaml }}"
    state: present
    wait: true
  loop:
  - homer/00-service.yml
  - homer/01-ingress.yml
  - homer/02-pvc.yml
  - homer/03-configmap.yml
  - homer/04-deployment.yml

# ------------------------------------------------------------------------------

- name: Setup openwebrx
  k8s:
    definition: "{{ lookup( 'template', item ) | from_yaml }}"
    state: present
    wait: true
  loop:
  - openwebrx/00-service.yml
  - openwebrx/01-ingress.yml
  - openwebrx/02-pvc.yml
  - openwebrx/03-secret.yml
  - openwebrx/04-deployment.yml

# ------------------------------------------------------------------------------

- name: Setup wunderground-uploader
  k8s:
    definition: "{{ lookup( 'template', item ) | from_yaml }}"
    state: present
    wait: true
  loop:
  - wunderground-uploader/00-deployment.yml

# ------------------------------------------------------------------------------

- name: Setup weather-sensor-bridge
  k8s:
    definition: "{{ lookup( 'template', item ) | from_yaml }}"
    state: present
    wait: true
  loop:
  - weather-sensor-bridge/00-deployment.yml
