---
- name: Install avahi-daemon Packages
  apt:
    name:
    - avahi-daemon
    state: present
  when:
  - ansible_facts.distribution is search("Ubuntu")
  notify: reboot

- name: Install nfs Packages
  apt:
    name:
    - nfs-common
    state: present
  notify: reboot
