---
- name: Setup the storage namespace
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 00-namespace.yml}

# ------------------------------------------------------------------------------

- name: Add nfs provisioner repo
  community.kubernetes.helm_repository:
    name: nfs-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

- name: Deploy nfs provisioner
  community.kubernetes.helm:
    name: nfs-provisioner
    chart_ref: nfs-provisioner/nfs-subdir-external-provisioner
    chart_version: 4.0.10
    values: "{{ lookup('template', 'nfs/01-chart-values.yml') | from_yaml }}"
    release_namespace: storage
    update_repo_cache: true
    wait: true
