---
- name: Remove nfs-provisioner release
  community.kubernetes.helm:
    name: nfs-provisioner
    purge: true
    namespace: storage
    state: absent
    wait: true

- name: Remove nfs-provisioner repo
  community.kubernetes.helm_repository:
    name: nfs-provisioner
    state: absent

# ------------------------------------------------------------------------------

- name: Delete the Storage namespace
  k8s:
    definition: "{{ lookup('template', '00-namespace.yml') | from_yaml }}"
    state: absent
    wait: true
