---
- name: Add nfs provisioner repo
  community.kubernetes.helm_repository:
    name: nfs-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

- name: Deploy nfs provisioner
  community.kubernetes.helm:
    name: nfs-provisioner
    chart_ref: nfs-provisioner/nfs-subdir-external-provisioner
    chart_version: 4.0.6
    values: "{{ lookup('template', '01-chart-values.yml') | from_yaml }}"
    namespace: nfs
    create_namespace: true
    wait: true
