---
apiVersion: v1
kind: Secret
metadata:
  name: openwebrx
  namespace: apps
type: Opaque
stringData:
  OPENWEBRX_ADMIN_USER: '{{ openwebrx_user }}'
  OPENWEBRX_ADMIN_PASSWORD: '{{ openwebrx_pass }}'
