---
- name: Add pihole helm repo
  community.kubernetes.helm_repository:
    name: pihole
    repo_url: https://mojo2600.github.io/pihole-kubernetes

# helm repo add mojo2600 https://mojo2600.github.io/pihole-kubernetes/
# helm repo update

- name: Deploy pihole chart
  community.kubernetes.helm:
    name: pihole
    chart_ref: pihole/pihole
    chart_version: 1.8.29
    values: "{{ lookup('template', '01-chart-values.yml') | from_yaml }}"
    release_namespace: dns-system
    update_repo_cache: true
    wait: true

- name: Finish pihole setup
  k8s:
    definition: '{{ lookup( item.type, item.path ) | from_yaml }}'
    state: present
    wait: true
  with_items:
  - {type: template, path: 02-middleware.yml}
  - {type: template, path: 03-ingress.yml}
