---
- hosts: master
  become: true
  roles:
  - cluster_control

- hosts: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  roles:
  - helm
  - storage
  - networking
  - monitoring
