---
- import_playbook: apps-destroy.yml

- hosts: cluster
  gather_facts: true
  become: true
  roles:
  - geoff_coppertop.k3s_roles.reset

- hosts: cluster
  become: true
  tasks:
  - name: Reboot the server and wait for it to come back up.
    reboot:
