---
- hosts: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  roles:
  - management/dns/pihole/teardown
  - management/traefik/teardown
  - management/dns/teardown
  - management/metallb/teardown
