---
- hosts: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  environment:
    # yamllint disable-line rule:truthy
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
  roles:
  - management/metallb/setup
  - management/dns/setup
  - management/dns/unbound/setup
  - helm
  - management/traefik/setup
