---
- hosts: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  roles:
  - management/metallb/setup
  - management/dns/setup
  - management/dns/unbound/setup
  - helm
  - management/traefik/setup
  - management/dns/pihole/setup
